name: superstore
description: A talos snowflake app
version: 0.1.6
auth:
  heimdallUrl: https://liberal-donkey.dataos.app/heimdall
logLevel: DEBUG  
sources:
  - name: snowflake
    type: snowflake
    connection:
      account: dz80249.central-india.azure
      username: "highonlife"
      password: "Lowonlife1"
      warehouse: mywarehouse
      database: "mydatabase"