name: superstore
description: A talos snowflake app
version: 0.1.12
auth:
  heimdallUrl: https://liberal-donkey.dataos.app/heimdall
logLevel: DEBUG  
sources:
  - name: snowflake
    type: snowflake
    connection:
      account: zg11815.central-india.azure
      username: "shraddha"
      password: "Itsasecret1"
      warehouse: mywarehouse
      database: "mydatabase"